### ISSUE TITLE
1.4.1 Links visueel in een tekst maar in de code los van de tekst

### ISSUE THREAD

**Issue by niekderksen** [WCAG-Audit-Discussions/NL-BE#11]
Voor het gemak gaan ik er vanuit dat het contrast niet voldoende is en dat kleur het enige middel is om de link visueel te onderscheiden.

`<p>Dat zijn ook makelaars in koffie, doch hun adres behoeft ge niet te weten. Ik pas er dus wel op, dat ik geen romans schrijf, of andere valse opgaven doe. Ik heb dan ook altijd opgemerkt dat mensen die zich met zoiets inlaten, gewoonlijk slecht wegkomen.</p> <div><a href="https://website.nl">Lees verder in Multatuli</a></div>`

Hierbij is de `<div>` met de link opgemaakt om direct achter de tekst te staan. Dus het ziet er zo uit:

> Dat zijn ook makelaars in koffie, doch hun adres behoeft ge niet te weten. Ik pas er dus wel op, dat ik geen romans schrijf, of andere valse opgaven doe. Ik heb dan ook altijd opgemerkt dat mensen die zich met zoiets inlaten, gewoonlijk slecht wegkomen. [Lees verder in Multatuli](https://website.nl)

Valt dit dan onder 1.4.1 Gebruik van kleur?

**Comment by rianrietveld** [comment]
Hey @niekderksen Dan je wel voor je issue.
Deze plek is niet om vragen te stellen maar we discussiëren hier hoe we de richtlijnen kunne interpeteren.

Het antwoord op je vraag is: Ja.
Iemand die kleurenblind is of slecht contrast ziet kan mogelijk de link niet onderscheiden van de rest van de tekst. De link moet een kleurcontrast hebben van ten minste 4.5 ten opzichte van de achtergrond en visueel zich onderscheiden van de tekst. Bijvoorbeeld door een onderstreping.

Voor dit soort vragen kun je terecht op de Fronteers slack (fronteersnl.slack.com) in het kanaal #accessibility.
