### ISSUE TITLE
Alleen Websites of ook PDF's en Apps?

### ISSUE THREAD

**Issue by ShadowBB** [WCAG-Audit-Discussions/NL-BE#2]
WCAG wordt ook gebruikt om PDF's en Apps te beoordelen. Willen we dergelijke vragen over de interpretatie van WCAG hier ook kwijt?

**Comment by rianrietveld** [comment]
Ja graag, alle discussie op een plek lijkt me zinvol.

**Comment by ShadowBB** [comment]
Lijkt mij ook handiger. Anders moeten er weer losse githubs aangemaakt worden voor die vraagstukken.
