### ISSUE TITLE
SC 1.4.10 Testen bij 1280px en inzoomen tot 400% of testen op 320px Responsive design modus (CTRL + SHIFT + M).

### ISSUE THREAD

**Issue by armenos** [WCAG-Audit-Discussions/NL-BE#37]
Aansluitend op discussie van SC 1.4.4 ben ik benieuwd hoe jullie hiertegen aankijken. Wanneer een website getest wordt op resolutie van 1280px (x 768px of 1024px hoogte) en wordt ingezoomd tot 400%. Kan het resultaat verschillen van de testmethode op 320px binnen responsive design modus (CTRL + SHIFT + M) developer tools van de Firefox of Chrome.

Binnen Failure Technique F102 worden beide methodes omschreven, maar ik ben van mening dat dit niet representatief is omdat de resultaten kunnen verschillen. 
Wanneer een website wordt bekeken op 320px (mobile scherm) komt er geen inzoomen van pas. Waardoor de echte problemen niet naar voren komen.  

Volgens mij is de SC 1.4.10 geschreven voor de mensen die niet anders kunnen dan inzoomen. En dus niet per se op 320px resolutie scherm de website bekijken.

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html
https://www.w3.org/WAI/WCAG21/Techniques/failures/F102

**Comment by Aircl0wn** [comment]
Ik hanteer momenteel https://github.com/w3c/wcag21/issues/883#issuecomment-384800487

> So the combined test for reflow, text-resize and text-spacing can be:
> 
> Set the browser window to 1280px wide.
Zoom in to 400%.
Check content & functionality is available, and no horizontal scrolling (in LTR languages).
Check text is at least 200% bigger.
Turn on text-sizing (e.g. with a [bookmarklet](https://www.w3.org/WAI/GL/wiki/Allowing_for_Spacing_Override#Bookmarklet_Procedure_.28for_Sites_without_Content_Security_Policies.29)).
Un-zoom through each media query, looking for overlaps / missing content.

Daarmee denk je 1.4.4, 1.4.10 en 1.4.12 af.

**Comment by Veyfeyken** [comment]
Er is consensus over de testmethode zoals beschreven door Alastair Campbell op https://github.com/w3c/wcag21/issues/883#issuecomment-384800487.

**Comment by MarjonBakker** [comment]
Ik zie dat er consensus is, al vind ik het niet duidelijk waarop die is gebaseerd. Het verschil op bevinding vaststellen tussen de 2 methodes is groot.

De [Duitse test](https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-1-4-10-inhalte-brechen-um) gaat uit van een beoordeling op een initiële viewport width van 320px. Een genoemd alternatief is de methode 1280px+zoom, maar daarbij wordt **uitdrukkelijk** gezegd dat er geen conclusies verbonden mogen worden als issues worden veroorzaakt door een te lage viewport height. Bovendien is bij verlies van functionaliteit de 320px-methode leidend:

> “Zur Prüfung des Verlusts von Informationen und Funktionalität ist die Prüfung bei 320px Viewport-Breite ausschlaggebend.”

De [Luxemburgse test](https://accessibilite.public.lu/en/raweb1.1/criteres.html#crit-10-11) gaat ook uit van een beoordeling op 320px, over 1280px+400% wordt niks gezegd.

Hoe zit het nou? De twee verschillende testmethoden lijken nogal impact te hebben in wat een author moet doen om een issue op te lossen.

**Comment by Veyfeyken** [comment]
Ter info, de testmethodologie van Deque:

Responsive Web Design Testing: When doing Responsive Web testing for tablet or phone breakpoints on a desktop computer, you do not have to test this checkpoint again if it has already been done for the Desktop breakpoint. It is redundant to test again.

1. Open the page in Chrome. Ensure that Chrome is displaying the page at its actual size with the site's provided CSS. (In other words, no zoom, no magnification, no user supplied CSS features are turned on).
2. Resize the browser viewport to one of the following (all are the equivalent to 320px width at 100% zoom):
 - 320px width by 256px height at 100% zoom OR
- 640px width by 512px height at 100% and then zoom to 200% OR
- 1280px width by 1024px height at 100% and then zoom to 400% zoom
- NOTE: Be sure to resize the viewport while at 100% zoom BEFORE applying the 200% or 400% zoom.
- NOTE: Be sure to CAREFULLY read the viewport resize instructions under "Recommended tools to size the browser viewport".
3. Confirm that "content" can be read without scrolling in more than one direction at a time. See "Things to think about" below for important details about how "content" is defined.
4. Exceptions: Content that is allowed to scroll horizontally: maps, diagrams, video, games, presentations, data tables (not individual cells), and interfaces where it is necessary to keep toolbars in view while manipulating content.

**Comment by MarjonBakker** [comment]
@Veyfeyken Dank voor de aanvulling. De testmethodologie van Deque heeft het alleen over horizontaal scrollen. Niet over verlies van informatie en functionaliteit. En met name bij die laatste zit de onduidelijkheid bij mij.
