### ISSUE TITLE
4.1.3 Statusberichten in combinatie met een live-search

### ISSUE THREAD

**Issue by DennisVanZanten** [WCAG-Audit-Discussions/NL-BE#51]
Hoi Allemaal,

Wij hebben een interne discussie over wanneer een live-search voldoet aan de WCAG2.1 en wanneer niet.
Bij de [understanding 4.1.3 Statusberichten](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) staat het volgende:

_"After a user presses a Search button, the page content is updated to include the results of the search, which are displayed in a section below the Search button. The change to content also includes the message "5 results returned" near the top of this new content. This text is given an appropriate role for a status message. A screen reader announces, "Five results returned"."_

Zoals te zien op de volgende afbeelding worden er zoekresultaten automatisch getoond nadat het invoerveld is ingevuld. Er werd bij ons aangegeven dat hier geen specifieke rollen voor nodig zijn, maar volgens bijvoorbeeld 4.1.3. lijkt het ons een verplichting om aan te geven dat er wel of geen zoekresultaten beschikbaar zijn nadat er woorden zijn getypt. 

![image](https://github.com/WCAG-Audit-Discussions/NL-BE/assets/132355027/57b34626-1e88-44b1-bff7-76793757513d)

Hoe gaan andere partijen hier mee om of wordt dit gewoon goedgekeurd en zo ja, met welke reden?

Alvast bedankt voor de reacties.

**Comment by rvantonisse** [comment]
Lijkt me een geval voor [3.2.2: On Input](https://www.w3.org/TR/WCAG22/#on-input), wanneer je de content dynamisch bijwerkt bij invoer.

Als je iets dergelijks hebt zoals bij het voorbeeld dat je aanhaalt, een bericht van het aantal zoekresultaten, dan heb je pas te maken met een statusbericht. Dynamisch content bijwerken is niet per se een status bericht.

Dat voorbeeld geeft ook een manier aan waarmee je op 3.2.2 kan voldoen bij wijzigingen aan context tijdens invoer; melden dat er nieuwe resultaten zijn. Maar dat verwacht je ook pas nadat de gebruiker klikt op "Toon resultaten".

**Comment by DennisVanZanten** [comment]
Kunnen wij dan zeggen dat een zoekfunctie dat resultaten toont op dezelfde pagina behoort tot een verandering van context? Het doel van de pagina verandert namelijk niet naar mijn idee, net als dat het doel van de zoekfunctie is om resultaten te tonen?

Kan dit wellicht anders fout zijn op basis van 4.1.2 naam, rol, waarde?
Het tonen van een nieuw blok, waarin de gebruiker kan navigeren naar een knop die meer resultaten toont, is dit dan ook een interface element?

**Comment by JuliaZjochova** [comment]
Ik zou het niet onder 3.2.2 plaatsen. Dit is geen grote verandering van context. De pagina heeft geen andere betekenis gekregen, toch? We zien de pagina niet op de screenshot, maar ik neem aan dat de pagina niet veranderd is. Leest de sr de resultaten voor of blijft het bij "Five results returned"?

**Comment by DennisVanZanten** [comment]
De sr leest momenteel niets voor en inderdaad blijft de gebruiker op dezelfde pagina.

Wij vinden dat zelf onlogisch, aangezien er wel iets wordt vertoond, wat normaliter niet aanwezig is. 
De inhoud van dit scherm verandert ook bij input telkens weer. 

Hoe ziet een gebruiker met een beperking dat de resultaten zichtbaar zijn of niet als ze geen terugkoppeling ontvangen?

**Comment by rvantonisse** [comment]
> Hoe ziet een gebruiker met een beperking dat de resultaten zichtbaar zijn of niet als ze geen terugkoppeling ontvangen?

Door verder te navigeren over de pagina. Sneller feedback, is gebruiksvriendelijker maar niet toegankelijker.

> Ik zou het niet onder 3.2.2 plaatsen. Dit is geen grote verandering van context. De pagina heeft geen andere betekenis gekregen, toch?

Het zoekformulier zelf is ook onderdeel van de context. Deze bestaat uit een tekstveld en een verzend knop, wat impliceert dat de gebuiker de resultaten te zien krijgt na het verzenden van het zoekformulier. Niet tijdens het invullen, of kort erna.

Het doel is nog steeds hetzelfde, zoekresultaten te zien krijgen.  Alleen is wanneer en hoe niet juist gecommuniceerd.

Dergelijke functionaliteit zie je wel in textboxes met een suggestiemenu, (e.g. met datalist element i.c.m. list attribuut op tekstinput) dit is een [listbox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/). Dus als je denkt dat dit het moet zijn, dan is het wel onder 4.1.2 af te keuren als rollen en status e.d. niet helder zijn. Daar lijkt het overigens naar mijn idee wel op. (X-je om te sluiten en Call to action knop voor alle zoekresultaten)
