### ISSUE TITLE
Ik stel graag Christophe Strobbe voor als medebeheerder! 🙂 

### ISSUE THREAD

**Issue by roelvangils** [WCAG-Audit-Discussions/NL-BE#69]
Hoi iedereen! 👋🏼

Ik vind deze plek op GitHub (nog steeds) een enorm waardevol initiatief en lees vaak met interesse mee. Maar ik ben éigenlijk gewoon een [lurker](https://nl.wikipedia.org/wiki/Lurker)! 🤷🏼‍♂️ De tijd ontbreekt me om issues te labelen of mee te discussiëren (wat wel de bedoeling was).

Daarom vind ik het niet echt fair dat ik nog steeds als een van de beheerders genoemd wordt in de [README](https://github.com/WCAG-Audit-Discussions/NL-BE/edit/main/README.md).

Bij ons ([Eleven Ways](https://elevenways.be/)) hebben we samen afgesproken – maar ik vraag eerst nog heel graag de toestemming aan de medebeheerders @rianrietveld, @JJdeGroot, @hidde, @ShadowBB, @julezrulez, @JuliaRietveld en @Aircl0wn – of het voor jullie ook goed is dat 🥁 Christophe Strobbe (@cstrobbe) mijn rol als Vlaamse medebeheerder mag overnemen.

Kunnen jullie bevestigen (met een 👍🏼 of zo) dat dat oké is? Christophe is een WCAG-expert met vele jaren op de teller en voert ook nog wekelijks audits uit. Hij is onze Principal Accessibility Consultant (die titel hebben we gepikt van Deque, wegens sjiek klinkend) en ik weet zéker dat hij heel waardevolle bijdragen zal kunnen leveren.

Een bijkomende reden voor deze vraag, is ook omdat we zelf ook steeds vaker onderzoeken voor Nederlandse klanten uitvoeren en we zijn er voorstander van om de beoordelingen zo veel mogelijk gelijk te trekken.

**Comment by ShadowBB** [comment]
Op dit moment ben ik zelfs minder dan een lurker helaas! Maar het lijkt me belangrijk dat de Vlaamse gemeenschap goed vertegenwoordigt blijft, dus ik vind het aanstellen van een vervanger een goed idee als mijn mening mee zou tellen ondanks dat. :)

**Comment by Aircl0wn** [comment]
(Uiteraard) geen bezwaar!

**Comment by roelvangils** [comment]
Thanks, guys and girls! En ieders mening telt hier natuurlijk even hard mee!

**Comment by cstrobbe** [comment]
Voor diegenen die mij nog niet zouden kennen: ik werk sinds 2001 in digitale toegankelijkheid (waarvan goed 20 jaar in de academische wereld, d.w.z. aan de KULeuven en de Hochschule der Medien) en ben voormalig lid van de WCAG-werkgroep (toen die nog zo heette).

**Comment by JuliaZjochova** [comment]
> Voor diegenen die mij nog niet zouden kennen: ...

Welkom, Christophe! Leuk dat je meedoet!

**Comment by julezrulez** [comment]
Ik vind dit een mooie aanpassing van het team.

**Comment by rianrietveld** [comment]
PR staat klaar.
Wie drukt er op merge?
https://github.com/WCAG-Audit-Discussions/NL-BE/pull/70

**Comment by rianrietveld** [comment]
@cstrobbe Je hebt een invite als maintainer.
