### ISSUE TITLE
Voorstel om onderwerp en besluiten uit het overleg onderzoeksbureau's hier als issues op te nemen.

### ISSUE THREAD

**Issue by rianrietveld** [WCAG-Audit-Discussions/NL-BE#75]
In de repository [Notulen overleg onderzoeksbureau's digitale toegankelijkheid Nederland](https://github.com/WCAG-Audit-Discussions/notulen-obnl), houden we bij wat er tijdens die overleggen is besproken en besloten.

Om die onderwerpen en de uitkomsten van de discussie ook hier vindbaar wil ik van de onderwerpen hier issues maken, met de bijbehorende labels. Zodat we besluiten kunnen terug vinden, of erop door kunnen discussiëren als er nog geen overeenkomst is.

Wat denken jullie hiervan? Mee eens?

**Comment by sander-nl** [comment]
Eerlijk gezegd lijkt me dat dubbel werk en daardoor foutgevoelig/bewerkelijk. 
We kunnen natuurlijk in issues hier wel verwijzen naar de notulen in die andere repo.

**Comment by rianrietveld** [comment]
Het gaat me vooral om de vindbaarheid van beslissingen, dis staat nu op 2 verschillende plekken

**Comment by julezrulez** [comment]
Ik twijfel. Soms zijn er punten die aandacht verdienen, soms niet.

**Comment by Aircl0wn** [comment]
Zou eea apart houden. Heb sowieso het idee dat die overleggen van origine niet bedoeld zijn voor dit soort topics, maar dat kan ik mis hebben, ze liepen al een tijdje voordat een paar jaar geleden aanhaakte.

Een consensus discussie zal hier sowieso afgemaakt moeten worden, omdat je ook inspraak wilt van mensen die niet bij de overleggen aanwezig zijn. 

Uiteraard kunnen we verwijzen of citeren als dat voor een issue dat hier geopend wordt relevant is.

**Comment by rianrietveld** [comment]
Ik zal het als agendapunt aandragen voor de volgende meeting.

**Comment by rianrietveld** [comment]
Wachten op besluit op te richten normcommissie over vastelgging besluiten
