### ISSUE TITLE
Labels toekennen

### ISSUE THREAD

**Issue by julezrulez** [WCAG-Audit-Discussions/NL-BE#9]
Voor het taggen hebben we al een voorzet staan in deze repository. Als het aantal ingebrachte issues groter wordt, wordt het terugvinden van een uitkomst lastiger. Een idee is om meerdere tags aan een uitkomst te hangen. Ik heb op mijn website tijdelijk een pagina neergezet met keywords/tags/labels. Mogelijk hebben anderen hier ook ideeën over.
Zie: [www.200ok.nl/wcag/taggen/](https://www.200ok.nl/wcag/taggen/)

**Comment by ShadowBB** [comment]
Goede lijst Jules! Tenzij iemand anders nog input heeft zal ik deze labels toevoegen aan de lijst van beschikbare labels.

**Comment by julezrulez** [comment]
Het zijn er wel veel hoor. Kunnen we ze misschien prefixen? Of sommige labels in een verzamellabel zetten?
Of denken jullie dat een lange lijst met labels nog wel bruikbaar blijft in github?

**Comment by ShadowBB** [comment]
Persoonlijk heb ik geen problemen met een lange lijst aan labels, vooral niet als het de moderators van deze GitHub zijn die ze toekennen. Maar als iemand liever een korte lijst wilt of wat bredere categorieën dan hoor ik het graag.

**Comment by Aircl0wn** [comment]
Hangt er een beetje vanaf of we diezelfde tags ook gebruiken in de HTML versie waar Rian mee bezig is. ik neem aan van wel? Het overnemen naar een markdown file is het probleem niet natuurlijk als een issue besproken is, maar het moet voor bezoekers ook wel overzichtelijk blijven er erin te zoeken straks?

**Comment by ShadowBB** [comment]
Hey Jules. Ik heb ze toegevoegd op de volgende na:

"Opsomming" omdat ik die te veel vind lijken op "lijsten".

"Zoekfunctie" omdat ik die te veel vind lijken op "zoeken"

"Techniek" omdat ik die niet identificerend vind voor issues.

Ik sluit het voor nu maar als je een case wilt maken voor bovenstaande ben ik all ears. :)
